INSERT INTO role (name) VALUES ('Photographer')
INSERT INTO role (name) VALUES ('Runner')
INSERT INTO role (name) VALUES ('Operator')
INSERT INTO role (name) VALUES ('Admin')
INSERT INTO Distance (name,length) values ('marathon',42)
INSERT INTO Distance (name,length) values ('half marathon',21)
Insert into user (login,password,role_id) values('admin','admin',4)
Insert into user (login,password,role_id) values('operator','operator',3)
INSERT INTO user (login,mail,name,surname,city,birthdate,role_id) VALUES ('antoni94','antoxa@ukr.net','Anton','Ivanchenko','Kiev','1995-10-10',2)
INSERT INTO user (login,mail,name,surname,city,birthdate,role_id) VALUES ('olya01','olyA@mail.ru','Olya','Pilipenko','Kharkiv','1991-02-01',2)

