INSERT INTO role (name) VALUES ('Photographer')
INSERT INTO role (name) VALUES ('Runner')
INSERT INTO role (name) VALUES ('Operator')
INSERT INTO role (name) VALUES ('Admin')
INSERT INTO Distance (name,length) values ('Марафон',42)
INSERT INTO Distance (name,length) values ('Полу-Марафон',21)
INSERT INTO Distance (name,length) values ('Полу-Марафон',6)
INSERT INTO Distance (name,length) values ('Марафон',7.5)
INSERT INTO Runner (name,surname,sex) values ('Михаил','Добрынин','MALE')
INSERT INTO Runner (name,surname,sex) values ('Юлия','Осипова','FEMALE')
INSERT INTO Runner (name,surname,sex) values ('Дмитрий','Гармаш','MALE')
INSERT INTO Runner (name,surname,sex) values ('Оксана','Бурова','FEMALE')
Insert into user (login,password,role_id) values('admin','admin',4)
Insert into user (login,password,role_id) values('operator','operator',3)
Insert into user (login,password,role_id) values('photographer','photographer',1)
INSERT INTO user (login,mail,name,surname,city,birthdate,role_id) VALUES ('antoni94','antoxa@ukr.net','Anton','Ivanchenko','Kiev','1995-10-10',2)
INSERT INTO user (login,mail,name,surname,city,birthdate,role_id) VALUES ('dandy','olyA@mail.ru','Olya','Pilipenko','Kharkiv','1991-02-01',2)
INSERT INTO user (login,mail,name,surname,city,birthdate,role_id,password) VALUES ('pathOf','olyA@mail.ru','Olya','Pilipenko','Kharkiv','1991-02-01',2,'ilai1111')
INSERT INTO Race (city,race_date,race_name,photo) values ('Харьков','2015-01-01','Любительский Забег','img_14.jpeg')
INSERT INTO Race (city,race_date,race_name,photo) values ('Киев','2016-05-05','Новогодний Марафон','img_145.jpeg')
INSERT INTO Race (city,race_date,race_name,photo) values ('Запорожье','2016-02-07','Веселые старты','img_1.jpeg')
INSERT INTO Race (city,race_date,race_name,photo) values ('Винница','2016-06-09','Грустный фининш','img_12.jpeg')
INSERT INTO result (Finish_time,Number,Distance_id,Runner_id,Race_id) VALUES ('01:32:15','787',1,1,1)
INSERT INTO result (Finish_time,Number,Distance_id,Runner_id,Race_id) VALUES ('00:29:15','назаров',3,1,3)
INSERT INTO result (Finish_time,Number,Distance_id,Runner_id,Race_id) VALUES ('00:12:15','215',4,1,4)
INSERT INTO result (Finish_time,Number,Distance_id,Runner_id,Race_id) VALUES ('00:44:06','777',2,2,2)
INSERT INTO result (Finish_time,Number,Distance_id,Runner_id,Race_id) VALUES ('00:44:06','778',2,1,2)
INSERT INTO result (Finish_time,Number,Distance_id,Runner_id,Race_id) VALUES ('01:32:05','345',1,2,1)
INSERT INTO result (Finish_time,Number,Distance_id,Runner_id,Race_id) VALUES ('01:32:05','2',1,3,2)
Insert into user (login,password,role_id) values('runner','runner',2)
INSERT INTO user (login,mail,name,surname,city,birthdate,role_id,runner_id,password) VALUES ('login','olyA@mail.ru','Olya','Pilipenko','Kharkiv','1991-02-01',2,1,'password')


